version: '3.3'

networks:
  network:
    #internal: true
    driver: bridge
#    name: ${NETWORK} ## > 3.3
#    enable_ipv6: false ## > 3.3
    attachable: true

services:
  php-apache:
    image: registry.kitafino.de/php8-base:latest
#    build:
#      context: ./php_apache
#      args:
#          php_version: '${PHP_VERSION}'
    depends_on:
      - database
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - network
  database:
    image: mysql:8.0.33
    env_file:
      - ./app/.env
      - .env
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: 'mypass'
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - network
